[completion]
copilot = false
activate_on_typing = true

[runtime]
auto_instantiate = false
auto_reload = "off"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
reactive_tests = true
on_cell_change = "lazy"

[display]
code_editor_font_size = 14
theme = "dark"
default_width = "medium"
cell_output = "below"
dataframes = "rich"

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[keymap]
preset = "default"
[keymap.overrides]

[package_management]
manager = "uv"

[server]
browser = "default"
follow_symlink = false

[language_servers.pylsp]
enable_pylint = false
enable_ruff = true
enable_mypy = true
enabled = true
enable_pydocstyle = false
enable_pyflakes = false
enable_flake8 = false

[formatting]
line_length = 79
